# Generated by Django 4.0.4 on 2022-05-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_food3_cal_alter_food3_carb_alter_food3_fat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('arm', 'arm'), ('back', 'back'), ('chest', 'chest'), ('legs', 'legs'), ('shoulder', 'shoulder')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='food3',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='food3',
            name='cal',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food3',
            name='carb',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food3',
            name='fat',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food3',
            name='prot',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
