# Generated by Django 4.0.4 on 2022-05-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_workout_alter_food3_options_alter_food3_cal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('arm', 'arm'), ('back', 'back'), ('chest', 'chest'), ('legs', 'legs'), ('shoulder', 'shoulder')], max_length=20)),
                ('img', models.ImageField(upload_to='workimgs')),
            ],
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
